services:
  backend:
    build: ./backend-MishCredit
    ports:
      - "5000:5000"
    volumes:
      - ./backend-MishCredit:/app
      - /app/node_modules

  frontend:
    build: ./frontend-MishCredit
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-MishCredit:/app
      - /app/node_modules
    depends_on:
      - backend