# docker compose para api y mongo sin acentos ni punto final
services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env

    ports:
      - "3000:3000"
    depends_on:
      - mongo
  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "8080:80"
    depends_on:
      - backend
volumes:
  mongo_data: {}
