# docker compose para api y mongo sin acentos ni punto final
services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  backend:
    build:
      context: ./backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/planificador
      - PORT=3000
      - UCN_BASE_PUCLARO=${UCN_BASE_PUCLARO}
      - UCN_BASE_HAWAII=${UCN_BASE_HAWAII}
      - HAWAII_AUTH=${HAWAII_AUTH}
      - USE_STUBS=${USE_STUBS:-true}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:8080}
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
volumes:
  mongo_data: {}
